### ISSUE TITLE
feature request: vscode link to log file

### ISSUE THREAD

**Issue by JoeySpronck** [daangeijs/deepops-slurmjob#1]
Would be nice if the vscode link is also written to the log file, so I can find it again
chat GPT says we should add the following to `setup_ssh_and_submit_job`:

        print("Interactive session started")
        vscode_link = f"vscode://vscode-remote/ssh-remote+{settings['username']}@{machine_name}:{port_number}{settings['home_folder']}?ssh={settings['key_location']}"        print(vscode_link)

        # Write the VSCode link to the log file
        stdin, stdout, stderr = ssh.exec_command(f"echo '{vscode_link}' >> {log_file}")
        
    ssh.close()

**Comment by daangeijs** [comment]
Thanks Joey for the suggestion, it is implemented in https://github.com/daangeijs/deepops-slurmjob/commit/2bcf414777c8fd055c1e26d8d5fa9f4e2bd3da5e.

If you install the new version of the package it should work, otherwise `pip uninstall slurmjob` and `pip install` the new package again.
