### ISSUE TITLE
Dynamic sbatch configuration arguments 

### ISSUE THREAD

**Issue by JoeySpronck** [daangeijs/deepops-slurmjob#2]
I would like to dynamically set the SBATCH qos/job priotity
Via sbatch this is possibe: sbatch --qos=high some_script.sh

Would be nice if we could do something similar with slurmjob:
slurmjob run --qos=high some_script.sh

**Comment by daangeijs** [comment]
Added in the latest version (https://github.com/daangeijs/deepops-slurmjob/commit/026b1ea5697956d794659ad53fc7fac27b17a82c)
You can pull the new update as following:
`pip install git+https://github.com/daangeijs/deepops-slurmjob.git`
