### ISSUE TITLE
vs-code link is echoed to wrong file if using windows

### ISSUE THREAD

**Issue by siemdejong** [daangeijs/deepops-slurmjob#4]
Posix paths are only used in 
https://github.com/daangeijs/deepops-slurmjob/blob/27c9f311c649a9ddb84d159c286abd19b1377037/slurmjob/run_interactive.py#L34

If they are already ensured here,
https://github.com/daangeijs/deepops-slurmjob/blob/27c9f311c649a9ddb84d159c286abd19b1377037/slurmjob/run_interactive.py#L75
this code
https://github.com/daangeijs/deepops-slurmjob/blob/27c9f311c649a9ddb84d159c286abd19b1377037/slurmjob/run_interactive.py#L95
would not output to 
`/home/siemdejong/homesiemdejonglogsslurm-21150.out`
but to
`/home/siemdejong/logs/slurm-21150.out`

**Comment by daangeijs** [comment]
So this would fix it?
`log_file = Path(settings['log_location']) / Path(f"slurm-{job_id}.out") `
to
`log_file = PurePosixPath(settings['log_location']) / PurePosixPath(f"slurm-{job_id}.out") `

**Comment by siemdejong** [comment]
Yes, the vscode uri is actually written to `/home/siemdejong/homesiemdejonglogsslurm-21150.out` and not to `/home/siemdejong/home/siemdejong/logs/slurm-21150.out` with the leading /home/siemdejong.

`PurePosixPath(settings['log_location']) / Path(f"slurm-{job_id}.out")` fixes it for me.

**Comment by daangeijs** [comment]
I assume that  /home/siemdejong/home/siemdejong/ is wrong right?
